### ISSUE TITLE
Opera Addon

### ISSUE THREAD

**Issue by shwetank** [jacobSingh/tabwrangler#103]
Hi,

Opera supports the chrome extensions model. It would be great if you could submit the extension to the [opera addons site](https://addons.opera.com) so that opera users could also use the extension. 

Regards,

**Comment by ssorallen** [comment]
I don't currently have the bandwidth to test in Opera, and I'd rather not submit it without using it constantly to know it's working well. If someone else is willing to test and deploy to Opera, I'd be willing to help support.

I'm going to close for now.
