### ISSUE TITLE
Import / Export

### ISSUE THREAD

**Issue by phraymond** [jacobSingh/tabwrangler#104]
Would like to be able to export the saved list.

**Comment by rprimus** [comment]
Mon Jan 23 21:41:51 GMT 2017

Hello.  I too would like to be able to export the URLs.    Am coming up close to the 500 limit, and would like to export the URLs before performing a clear.

This [StackoverFlow](https://stackoverflow.com/questions/23160600/chrome-extension-local-storage-how-to-export) answer shows to export to a JSON file that is downloadable by user.

Could this be added?

Cheers.

**Comment by ingorichter** [comment]
I'm currently working a fix for this. It's in my clone and I'm nearly done with it.

**Comment by sergeevabc** [comment]
Aggrrhhh! Export does not work as follows (version 6.4.1 within FF 63.0.3)…

![](https://images.vfl.ru/ii/1545936297/b8431bcc/24750635.gif)

**Comment by ingorichter** [comment]
Was this working with a previous version of FF? I’m currently away from a real machine so I can’t take a look myself for another week.

**Comment by ssorallen** [comment]
It's definitely busted. I found the exception that's happening but haven't had a chance to look into why that's happening yet. Issue #261 is where we can track this.

**Comment by ssorallen** [comment]
@sergeevabc This is fixed in #261 and will go into the next release, v6.5.0.
