### ISSUE TITLE
Tabs get negative countdown

### ISSUE THREAD

**Issue by netromdk** [jacobSingh/tabwrangler#110]
In some cases the countdown turns negative but keeps counting further down, which means that the tab never gets put into the corral. The only way to reset is to change the inactivity duration field in options.

Sometimes it happens when I sleep/wake up my laptop. Sometimes it just happens after a while when I look at the tab lock tab. Unfortunately I'm not able to continuously reproduce it.

An example:
<img width="680" alt="example" src="https://cloud.githubusercontent.com/assets/5989057/22993592/d262d28a-f3c3-11e6-9e26-881eb196037a.png">

Make sure to enforce values to be >= 0 and if a value is negative for any reason then put into corral.

Thanks

**Comment by ssorallen** [comment]
Thanks, I will address this one. I will check it out while implementing system sleep in #5.
