### ISSUE TITLE
Bug: Must move mouse off icon and back on to get "close" action

### ISSUE THREAD

**Issue by rynowin** [jacobSingh/tabwrangler#115]
Found in v4.1.0, (w/Chrome  56.0.2924.87)

Steps to reproduce:
1. Make sure there are multiple tabs wrangled in the same timing "group".
2. Open the list of wrangled tabs.
3. Mouse over the icon of the first tab in the list, which reveals the "X" to remove the tab from the list.
4. Click the X, but don't move your mouse afterwards.
5. Observe: Your mouse is now hovering directly over the icon of the _next_ tab, but the icon is still showing, and if you click, you can't close the tab. In order to close the next tab, you need to move your mouse away, then back onto the icon, in order to close.

Impact: I very often will go clean out my list of tabs, and usually will have a bunch of tabs I want to close in a row. I usually am able to do this very easily and efficiently, but leaving my mouse in the same place and clicking repeatedly. Now, this common and important task is less efficient, as I have to move the mouse away and back to the button for every tab I want to close.

Let me know if I can provide any more detail!

**Comment by ssorallen** [comment]
Thanks for the bug report. I pushed a fix that will be in the next release (likely v4.2.0).
