### ISSUE TITLE
Where to find tab corral list when Chrome Crashes

### ISSUE THREAD

**Issue by swmediuos** [jacobSingh/tabwrangler#126]
Computer crashed and chrome along with it. My chrome profile seemed to be corrupted. Previously it was ok but this time my corral didn't come back.

Is there a place in Chrome files (C:\Users\<user>\AppData\Local\Google\Chrome\User Data\Default) where I can recover the list?

**Comment by ssorallen** [comment]
Tab Wrangler stores the corral in Local Storage. This StackOverflow answer might point you to the right location:

https://superuser.com/questions/507536/where-does-google-chrome-save-localstorage-from-extensions

**Comment by ssorallen** [comment]
Let me know if you were able to recover. Since Chrome profiles are outside the scope of extensions, I don't believe there is anything for the extension to do here.
