### ISSUE TITLE
Store the # of tabs "wrangled" over time

### ISSUE THREAD

**Issue by jacobSingh** [jacobSingh/tabwrangler#14]
Show a little stats counter at the bottom of the corral?

**Comment by ssorallen** [comment]
I wanted to make this value prominent to show how much value Tab Wrangler is adding. The search input didn't need to be so wide, so I placed it next to the value:

<img width="705" alt="screen shot 2017-02-14 at 9 51 26 am" src="https://cloud.githubusercontent.com/assets/29612/22941674/4f80c0da-f29b-11e6-8276-9ffec540e5f0.png">
