### ISSUE TITLE
Result Count

### ISSUE THREAD

**Issue by eorroe** [jacobSingh/tabwrangler#141]
Would really love if after searching, right next to the search input it showed a number of results found.

**Comment by ssorallen** [comment]
I added the result count to the scrolling header in order to indicate the results are filtered if you're scrolled down the list.

<img width="695" alt="screen shot 2017-07-19 at 9 09 25 am" src="https://user-images.githubusercontent.com/29612/28377528-e6dd4da0-6c61-11e7-929d-ecbe83636e92.png">

**Comment by eorroe** [comment]
Awesome, when's the next release coming? and is it possible for you to open an issue or use projects to indicate what updates are coming in the next release? I'd love to know what's in the works without having to comment on an issue

**Comment by ssorallen** [comment]
Oh sure, I've never used Projects before but I can take a look. The releases happen whenever I feel like I've sufficiently tested the new features, which is an arbitrary amount of time right now.
