### ISSUE TITLE
Anonymous usage stat collection

### ISSUE THREAD

**Issue by jacobSingh** [jacobSingh/tabwrangler#31]
It would be nice to compile how people are using TW.  What options are set, how many tabs closed, etc.

**Comment by ssorallen** [comment]
Going to close this as I don't plan to address it. Usage data might be useful for a project with more active development, but the tradeoff of asking people to volunteer data when I don't think the project can make good use of it is difficult.

I'm also a privacy and security stickler, and going from collecting no data to collecting even a little adds a lot of responsibility and vulnerability to this extension. I'm happy maintaining that this extension collects zero information from its users (aside from the install, uninstall, and active user counts that the Chrome Store collects for all extensions).
