### ISSUE TITLE
Predict and auto-pin tabs based bases on my pin history

### ISSUE THREAD

**Issue by saitanay** [jacobSingh/tabwrangler#52]
When ever I pin a tab, train Google Prediction API with the title of the pinned tab. Add a new option which allows tabwrangler to auto-pin tabs.

Once you have a history of atleast 100 pinned tabs, each time a tab is opened and not closed by the user after set time, then instead of directly closing the tab, tab wrangler will ask prediction api if the title of the tab is a match. And the tab is automatically pinned if prediction api gives a go.

For each autopinned tab, user should be able to mark if the autopin was helpful and this feedback should be used to further train the prediction api.

The prediction and training set should be on a per user basis (obviously).

Resources: https://developers.google.com/prediction/

**Comment by ssorallen** [comment]
This does sound cool, but I agree this is beyond the scope of Tab Wrangler for the time being. I'm happy to look at any pull requests though.
