### ISSUE TITLE
Tabs are not closed if the PC is locked

### ISSUE THREAD

**Issue by MokretsovD** [jacobSingh/tabwrangler#62]
My computer worked all night running Chrome, in the morning I saw the following:

![image](https://f.cloud.github.com/assets/4973972/899169/fc0cf456-fb35-11e2-80da-f6d0f270f01c.png)

**Comment by ssorallen** [comment]
The bug captured here is better captured in #110. I'm going to close this in favor of that one. 

This is related to #5, which would add idle tracking to disable the countdown when the system sleeps.
