### ISSUE TITLE
Feature to convert tabs to bookmarks

### ISSUE THREAD

**Issue by RodolfoNetto** [jacobSingh/tabwrangler#63]
Tab wrangler - chromium/ubuntu 13.04 - lost my tabs. I did some cache cleaning. Where tab wrangler saves the tabs? Does it use the Bookmarks? That would be nice. Also, could I export the saved tabs to a bookmark file?

I apologize if this is not the place to ask these questions, but I really like the extension and have told about it to my friends on FB. I just hope they won't loose tabs. :)

Thanks!

**Comment by jm3** [comment]
An alternate idea, instead of saving dead tabs to bookmarks, would be to just push them to a bookmarking service e.g. Pinboard, tagged "closed" or some such.

**Comment by rynowin** [comment]
> having a feature to save the currently closed tabs to the bookmarks sounds like it could be interesting
+1

**Comment by ssorallen** [comment]
Converting wrangled tabs into bookmarks seems out of scope for Tab Wrangler for the time being. I'm going to close this to focus on the core features of TW, closing tabs on a regular interval.
