### ISSUE TITLE
Feature request: better tab grouping

### ISSUE THREAD

**Issue by a-b** [jacobSingh/tabwrangler#65]
Usually user browsing has some "Subject" it would be really great to find some way to group tabs by subject like: "finding new apartment" or "research on vim like chrome extensions".

Phase 1: We can try to clusterize tab open events by time, to better detect this groups
Phase 2: we can try to parse meta or website titles to compose group name.

**Comment by ssorallen** [comment]
This idea sounds interesting, but I believe it is out of scope for Tab Wrangler. chrome://history or other bookmark management extensions might be a good place to find this functionality. I'm always happy to review pull requests around this though.
