### ISSUE TITLE
Shortcut key for "Close tab and save to corral"

### ISSUE THREAD

**Issue by boxfoot** [jacobSingh/tabwrangler#69]
I'm finding that I use the feature to close a tab and move it to the corral a lot - it's helpful when I want to deal with X in a couple hours - worth getting out of my way, but not worth creating a bookmark for.

It's currently a lot of clicks to find.  Would be great if there could be a keyboard shortcut for that.  Since CTRL-W is "Close Tab," maybe "CTRL-SHIFT-W"?

**Comment by edjroot** [comment]
I know this issue was opened a long time ago, but since it was referenced recently I believe it's worth mentioning that `Ctrl+Shift+W` is the shortcut for closing the current window. Also, according to the [docs](https://developer.chrome.com/extensions/commands),

> Certain Chrome shortcuts (e.g. window management) always take priority over Extension Command shortcuts and can not be overwritten.

**Comment by ssorallen** [comment]
@edjroot `Ctrl+Shift+W` would work on MacOS because the shortcut for closing the current window is `Cmd+Shift+W`. Are you a Windows or Linux user? What would be appropriate on those platforms?

**Comment by edjroot** [comment]
Hmm, I didn't know that! I use both Linux and Windows and [all shortcuts are the same](https://support.google.com/chrome/answer/157179?hl=en) for them (and I guess Mac too, except it's always `Cmd` in place of `Ctrl`). I don't have any particular suggestion, but it's probably a good idea to use the same combinations across OSs anyway.

**Comment by ssorallen** [comment]
I'm going to go with `Ctrl+Space+W`. The hand position feels quite natural since your thumb is resting on the spacebar.

**Comment by ssorallen** [comment]
I chose the following shortcuts to start:

Mac: `Ctrl+Shift+W`
Other: `Ctrl+Shift+E`

These are configurable by going to chrome://extensions/configureCommands in Chrome. If you have a more suitable suggestion for a default for Windows or Linux, I'm happy to change the default.

**Comment by edjroot** [comment]
It's fine by me!
