### ISSUE TITLE
All tabs checked by default, cannot uncheck them (blank rule)

### ISSUE THREAD

**Issue by ElijahLynn** [jacobSingh/tabwrangler#71]
I had this working then it stopped working and I didn't know why. I added one URL to the whitelist and didn't realize I had also added a blank rule. When a blank rule is added, all URLs are checked by default and you cannot uncheck them

I propose not allowing anyone to save a blank rule as it is pretty easy to do.

**Comment by ssorallen** [comment]
The form can no longer be submitted if the whitelist input is empty or contains only spaces. You shouldn't be able to add empty rules any more.
