### ISSUE TITLE
Add Warning to "Clear List"

### ISSUE THREAD

**Issue by CaptainDDL** [jacobSingh/tabwrangler#76]
Could you add a warning to the "clear list" button? 

Just a few minutes ago, I narrowed down the list of tabs via the search, and hit clear list thinking it would only clear those tabs. Unfortunately I lost my 300+ wrangled tabs. :-1: While the functionality I mentioned would be awesome, could you please add a warning popup to the clear list button in the interim? Thanks!

**Comment by ssorallen** [comment]
This one bit me too. I made the button clear only the visible tabs in my fork: https://github.com/ssorallen/tabwrangler/commit/63e62024eb48cf28dc470698a1cc1848c6444f72
