### ISSUE TITLE
Is this better than sonntag/tabshepherd? If so, how?

### ISSUE THREAD

**Issue by Wizek** [jacobSingh/tabwrangler#89]
https://github.com/sonntag/tabshepherd

**Comment by ssorallen** [comment]
sonntag/tabshepherd forked jacobSingh/tabwrangler on Mar 5, 2013: https://github.com/sonntag/tabshepherd/tree/5a500da3fd6fd937b9436f52424ba725fcf37608

You'll have to poke around that code to see if it offers anything better or newer than Tab Wrangler.

**Comment by ssorallen** [comment]
TabSheperd's latest commit is from 2015. I'll be maintaining TabWrangler going forward, so feel free to mention any features you liked from TabSheperd.
