### ISSUE TITLE
tab wrangler doesn't pop up list stopped working

### ISSUE THREAD

**Issue by garthgoodson** [jacobSingh/tabwrangler#90]
When I click the tab-wrangler icon it now often does not pop up list of closed tabs.  It used to work fine.  I tried restarting the browser, but no help.  The button is marked as pushed in, but no list.

Chrome on Linux version Version 40.0.2214.115 (64-bit).  Tab Wrangler 3.1

**Comment by ssorallen** [comment]
This is a duplicate of #101. I suspect it doesn't seem to work because it is so slow.
