### ISSUE TITLE
add ability to add a tab to pocket and close it immediately from the tab list

### ISSUE THREAD

**Issue by teolemon** [jacobSingh/tabwrangler#91]

**Comment by ssorallen** [comment]
By "pocket" do you mean the [Pocket](https://chrome.google.com/webstore/detail/save-to-pocket/niloccemoadcdkdjlinkgdfekeahmflj?hl=en) Chrome Extension? I'm not sure there's a way to interact between extensions like that. I'm going to close this, but let me know if you have more info.

**Comment by jezcope** [comment]
I'd be really interested in this feature too. I don't think you'd need to interact with another extension as you could call the [Pocket API](https://getpocket.com/developer/) directly from your own extension.

**Comment by ssorallen** [comment]
@jezcope Sounds like an interesting integration. I'd be interested to see more, I re-opened the issue and updated the description about the Pocket API.
