### ISSUE TITLE
Feature Request: Corral Now

### ISSUE THREAD

**Issue by darkpixel** [jacobSingh/tabwrangler#92]
I'd love to have a feature where you can click a specific tab to put into the corral immediately.

Frequently I'll have a bunch of tabs open while doing research, and I'd love to be able to pick one to 'save for later' while I'm drilling to the bottom of ~100 open tabs.

**Comment by ssorallen** [comment]
It's unfortunately impossible to [add items to context menus on tabs](https://superuser.com/questions/473960/how-do-you-add-items-to-google-chrome-tab-context-menu). Extensions are limited to adding context menus on elements within a rendered HTML page and the context menu of the extension's icon in the URL bar row.

You can already right click inside the page you are on, choose the Tab Wrangler menu, and select "Close tab and save URL Immediately" like in this screenshot:

<img width="564" alt="screen shot 2017-02-19 at 12 59 52 pm" src="https://cloud.githubusercontent.com/assets/29612/23106507/5600055e-f6a3-11e6-8555-20fbea338f8b.png">

**Comment by ssorallen** [comment]
Watch #69 too; I'm going to add a configurable keyboard shortcut for wrangling the current active tab.
